Appdistribution
WebEducationPlatform/CRM pull request #576
Opened 2019-08-20 16:04 UTC by nomokonov

Распределение вх заявок на HR -ов по % соотношению

CREATE TABLE `user_routes` (
  `user_routes_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_route_type` varchar(255) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `user_id` bigint(20) NOT NULL,
  PRIMARY KEY (`user_routes_id`),
  KEY `FK6q0o9pglykxq48w3qmdkahtxn` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8

2019-08-20 17:21 UTC, shpi0 requested changes

2019-08-20 17:21 UTC, shpi0 commented on src/main/java/com/ewp/crm/models/UserRoutes.java
> +    private User user;
Цикличиские связи убрать

2019-08-20 18:51 UTC, nomokonov commented on src/main/java/com/ewp/crm/models/UserRoutes.java
> +    private User user;
Все таки используются функционал со связями тут

Set<UserRoutes> userRoutes = hrUser.getUserRoutes() != null ? hrUser.getUserRoutes(): new HashSet<>();
                UserRoutes uRoutes = UserRoutesDto.getUserRoutesFromDto(routesDto);
                uRoutes.setUser(hrUser);
                if (userRoutes.contains(uRoutes)){
                    for (UserRoutes rout: userRoutes ) {
                        if (rout.equals(uRoutes)){
                            rout.setWeight(uRoutes.getWeight());
                        }
                    }
                } else {
                    userRoutes.add(uRoutes);
                }
                hrUser.setUserRoutes(userRoutes);
                update(hrUser);

2019-08-20 20:55 UTC, shpi0 requested changes

2019-08-20 20:55 UTC, shpi0 commented on src/main/java/com/ewp/crm/models/UserRoutes.java
> +    private User user;
Значит логику нужно изменить, циклические зависимости убрать

2019-08-22 09:12 UTC, nomokonov commented on src/main/java/com/ewp/crm/models/UserRoutes.java
> +    private User user;
Изменил логику: вынес  работу с UserRoutes в отдельные сло и сервиса и репо

2019-08-26 18:24 UTC, shpi0 requested changes

2019-08-26 18:24 UTC, shpi0 commented on src/main/java/com/ewp/crm/service/impl/UserRoutesServiceImpl.java
> +    public List<UserRoutesDto>  getUserByRoleAndUserRoutesType(String userRole, String userRouteType){
убрать дао из сервисного слоя

2019-08-26 18:24 UTC, shpi0 commented on src/main/java/com/ewp/crm/service/impl/UserServiceImpl.java
> +        if (routetype == null) {
здесь аналогично

2019-08-27 03:37 UTC, nomokonov commented on src/main/java/com/ewp/crm/service/impl/UserRoutesServiceImpl.java
> +    public List<UserRoutesDto>  getUserByRoleAndUserRoutesType(String userRole, String userRouteType){
Убрал

2019-08-31 17:33 UTC, shpi0 approved these changes

2019-08-31 17:34 UTC, merged