feature/APIforWorkWithHistory
WebEducationPlatform/CRM pull request #618
Opened 2019-09-12 02:24 UTC by kozionov

API для работы с историей

2019-09-12 17:16 UTC, Sorokinsta requested changes

2019-09-12 17:16 UTC, Sorokinsta commented on src/main/java/com/ewp/crm/controllers/rest/api/ClientHistoryApiRestController.java
> +        this.clientHistoryService = clientHistoryService;
сделатть все сервисы через конструктор

2019-09-12 17:16 UTC, Sorokinsta commented on src/main/java/com/ewp/crm/controllers/rest/api/ClientHistoryApiRestController.java
> +    @PutMapping("/{clientId}")
все через post с разным назвванием

2019-09-12 17:16 UTC, Sorokinsta commented on src/main/java/com/ewp/crm/repository/interfaces/CallRecordRepository.java
> +    CallRecord getByClientHistory_Id(Long id);
переименовать в соответствии с конвенцией

2019-09-13 03:20 UTC, kozionov commented on src/main/java/com/ewp/crm/controllers/rest/api/ClientHistoryApiRestController.java
> +        this.clientHistoryService = clientHistoryService;
Исправил

2019-09-13 03:20 UTC, kozionov commented on src/main/java/com/ewp/crm/controllers/rest/api/ClientHistoryApiRestController.java
> +    @PutMapping("/{clientId}")
Исправил

2019-09-13 03:20 UTC, kozionov commented on src/main/java/com/ewp/crm/repository/interfaces/CallRecordRepository.java
> +    CallRecord getByClientHistory_Id(Long id);
Исправил

2019-09-16 17:09 UTC, merged